#!/usr/bin/env python3
"""One synthetic package, described three times in three config languages.

The corpus is a layered Python package: `zones` stacked subpackages, `modules`
files in each, and every file importing one file from the layer directly beneath
it. It is deliberately **clean**. A dirty corpus measures how fast a tool can
give up, and the first violation could be one file in, so the number would say
more about the order of a directory listing than about the tool. A clean graph
has no early exit in it: to answer "yes" every tool has to read every file and
resolve every edge, which is the honest worst case and also the case CI pays on
every green run.

The three configs express the *same* rule — a layer may import downward and not
upward — in each tool's own idiom, because a benchmark where one tool is asked an
easier question is not a benchmark. `.zone` stacks zones low to high, and both
rivals list layers high to low; the reversal is theirs, not ours.

Nothing here is committed. The tree is generated into a temporary directory, so
the corpus can be resized to taste and never rots in the repository.
"""

from __future__ import annotations

from pathlib import Path

PACKAGE = "acme"


def build(dest: Path, *, zones: int, modules: int) -> int:
    """Write the whole corpus under `dest` and return how many files it holds."""
    names = [f"zone{i:02d}" for i in range(zones)]
    root = dest / PACKAGE
    root.mkdir(parents=True, exist_ok=True)
    (root / "__init__.py").write_text("", encoding="utf-8")

    written = 1
    for depth, name in enumerate(names):
        here = root / name
        here.mkdir(exist_ok=True)
        (here / "__init__.py").write_text("", encoding="utf-8")
        written += 1
        for n in range(modules):
            (here / f"m{n:02d}.py").write_text(body(names, depth, n, modules), encoding="utf-8")
            written += 1

    (dest / f"{PACKAGE}.zone").write_text(contract(names), encoding="utf-8")
    (dest / ".importlinter").write_text(importlinter(names), encoding="utf-8")
    (dest / "tach.toml").write_text(tach(names), encoding="utf-8")
    return written


def body(names: list[str], depth: int, n: int, modules: int) -> str:
    """One module: an import of the layer below, plus something to hold a name.

    The bottom layer imports nothing internal, which is what makes the stack a
    stack rather than a ring. Every file also imports from the standard library,
    so each tool has to decide an outside module is outside — the cheap case, but
    a case, and one every real file exercises.
    """
    lines = ["from __future__ import annotations", "", "import json"]
    if depth:
        below = names[depth - 1]
        lines.append(f"from {PACKAGE}.{below}.m{n % modules:02d} import lower")
    lines += [
        "",
        "",
        "def lower() -> str:",
        f'    return json.dumps("{names[depth]}.m{n:02d}")',
        "",
    ]
    return "\n".join(lines)


def contract(names: list[str]) -> str:
    """The `.zone` contract: zones low to high, so each may reach only downward.

    `facade` names the package's own `__init__.py`. Every governed file must be
    claimed by exactly one zone, and the top-level init belongs to no layer — so
    without this line the corpus would be judged dirty for a reason that has
    nothing to do with the rule under test, and the race would be rigged against
    the only tool that noticed.
    """
    width = max(len(name) for name in names)
    stack = "\n".join(f"    {name:<{width}} {PACKAGE}/{name}/**" for name in names)
    return f"""\
// Generated by bench/corpus.py — a layered package with no violation in it, so
// every tool racing here has to read the whole graph to say so.
package {PACKAGE} {{
    root     .
    language python
    facade   {PACKAGE}/__init__.py
}}

zones {{
{stack}
}}

forbid cycles across directories
"""


def importlinter(names: list[str]) -> str:
    """The same rule as an import-linter `layers` contract, high to low."""
    stack = "\n".join(f"    {name}" for name in reversed(names))
    return f"""\
# Generated by bench/corpus.py — the same rule the .zone contract states.
[importlinter]
root_package = {PACKAGE}

[importlinter:contract:layers]
name = A layer may import downward only
type = layers
layers =
{stack}
containers =
    {PACKAGE}
"""


def tach(names: list[str]) -> str:
    """The same rule again, as tach modules with explicit dependencies.

    Spelled with `depends_on` rather than tach's own layers, because an explicit
    edge list is the part of tach's config that has been stable across its
    releases — a benchmark should not be the first thing to break when a rival
    renames a key.
    """
    rows = [f'[[modules]]\npath = "{PACKAGE}"\ndepends_on = []\n']
    for depth, name in enumerate(names):
        below = f'"{PACKAGE}.{names[depth - 1]}"' if depth else ""
        rows.append(f'[[modules]]\npath = "{PACKAGE}.{name}"\ndepends_on = [{below}]\n')
    blocks = "\n".join(rows)
    return f"""\
# Generated by bench/corpus.py — the same rule the .zone contract states.
source_roots = ["."]

{blocks}"""
